server:
 port: 8080
 servlet:
  context-path: /loan

spring:
 profiles:
  active: ${SPRING_PROFILES_ACTIVE:test}
 jpa:
  properties:
   hibernate:
    jdbc:
     time_zone: UTC

doc:
 api-docs:
  path: /api-docs
 swagger-ui:
  path: /swagger-ui.html

app:
 pagination:
  default-page: 0
  default-size: 36

jwt:
 secretKey: ${JWT_SECRET_KEY:loan-secret}
 expirationMs: ${JWT_EXPIRATION_MS:600000}